(ns copackaged_optics.actor
  "copackaged_optics clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). Co-packaged optics / 光電融合 optical interconnect.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; OpticalEngine
   {:db/ident :copackaged_optics.OpticalEngine/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :copackaged_optics.OpticalEngine/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.OpticalEngine/generation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.OpticalEngine/lanes :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.OpticalEngine/aggregateTbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.OpticalEngine/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.OpticalEngine/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ElectroOpticTile
   {:db/ident :copackaged_optics.ElectroOpticTile/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :copackaged_optics.ElectroOpticTile/engineId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.ElectroOpticTile/tileType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.ElectroOpticTile/channels :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.ElectroOpticTile/powerPjPerBit :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.ElectroOpticTile/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.ElectroOpticTile/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; FiberLink
   {:db/ident :copackaged_optics.FiberLink/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :copackaged_optics.FiberLink/engineId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.FiberLink/fiberType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.FiberLink/reachM :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.FiberLink/dataRateGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.FiberLink/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.FiberLink/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; SerdesLane
   {:db/ident :copackaged_optics.SerdesLane/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :copackaged_optics.SerdesLane/engineId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.SerdesLane/index :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.SerdesLane/modulation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.SerdesLane/dataRateGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.SerdesLane/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.SerdesLane/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; OpticalSwitch
   {:db/ident :copackaged_optics.OpticalSwitch/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :copackaged_optics.OpticalSwitch/engineId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.OpticalSwitch/radix :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.OpticalSwitch/technology :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.OpticalSwitch/insertionLossDb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.OpticalSwitch/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.OpticalSwitch/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; LinkBudget
   {:db/ident :copackaged_optics.LinkBudget/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :copackaged_optics.LinkBudget/engineId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.LinkBudget/txPowerDbm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.LinkBudget/rxSensitivityDbm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.LinkBudget/marginDb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.LinkBudget/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :copackaged_optics.LinkBudget/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"OpticalEngine" "ElectroOpticTile" "FiberLink" "SerdesLane" "OpticalSwitch" "LinkBudget"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "copackaged_optics: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "copackaged_optics: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "copackaged_optics: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── OpticalEngine ────────────────────────────────────────────────────────────────
(defn create-optical-engine
  "Create a OpticalEngine."
  [port data]
  (require-fields data ["name" "generation"])
  (let [id (new-id "cpo_opt")
        e {:db/id id
           :copackaged_optics.OpticalEngine/id id
           :copackaged_optics.OpticalEngine/name (get data :name)
           :copackaged_optics.OpticalEngine/generation (get data :generation)
           :copackaged_optics.OpticalEngine/lanes (as-long (get data :lanes))
           :copackaged_optics.OpticalEngine/aggregateTbps (as-double (get data :aggregateTbps))
           :copackaged_optics.OpticalEngine/createdAt (now)
           :copackaged_optics.OpticalEngine/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-optical-engines
  "List OpticalEngine with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-optical-engines port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :copackaged_optics.OpticalEngine/id))
         rows (apply-filters rows (:filter opts) [:copackaged_optics.OpticalEngine/name :copackaged_optics.OpticalEngine/generation :copackaged_optics.OpticalEngine/lanes :copackaged_optics.OpticalEngine/aggregateTbps])]
     (paginate rows opts))))

(defn get-optical-engine
  "Retrieve a OpticalEngine by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-optical-engine port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-optical-engine
  "Update a OpticalEngine; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :copackaged_optics.OpticalEngine/name (get data :name)]))
                   (cond-> (contains? data :generation) (conj [:db/add id :copackaged_optics.OpticalEngine/generation (get data :generation)]))
                   (cond-> (contains? data :lanes) (conj [:db/add id :copackaged_optics.OpticalEngine/lanes (as-long (get data :lanes))]))
                   (cond-> (contains? data :aggregateTbps) (conj [:db/add id :copackaged_optics.OpticalEngine/aggregateTbps (as-double (get data :aggregateTbps))]))
                   (conj [:db/add id :copackaged_optics.OpticalEngine/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-optical-engine
  "Delete a OpticalEngine."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ElectroOpticTile ────────────────────────────────────────────────────────────────
(defn create-electro-optic-tile
  "Create a ElectroOpticTile."
  [port data]
  (require-fields data ["tileType" "channels"])
  (let [id (new-id "cpo_ele")
        e {:db/id id
           :copackaged_optics.ElectroOpticTile/id id
           :copackaged_optics.ElectroOpticTile/engineId (get data :engineId)
           :copackaged_optics.ElectroOpticTile/tileType (get data :tileType)
           :copackaged_optics.ElectroOpticTile/channels (as-long (get data :channels))
           :copackaged_optics.ElectroOpticTile/powerPjPerBit (as-double (get data :powerPjPerBit))
           :copackaged_optics.ElectroOpticTile/createdAt (now)
           :copackaged_optics.ElectroOpticTile/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-electro-optic-tiles
  "List ElectroOpticTile with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-electro-optic-tiles port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :copackaged_optics.ElectroOpticTile/id))
         rows (apply-filters rows (:filter opts) [:copackaged_optics.ElectroOpticTile/engineId :copackaged_optics.ElectroOpticTile/tileType :copackaged_optics.ElectroOpticTile/channels :copackaged_optics.ElectroOpticTile/powerPjPerBit])]
     (paginate rows opts))))

(defn get-electro-optic-tile
  "Retrieve a ElectroOpticTile by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-electro-optic-tile port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-electro-optic-tile
  "Update a ElectroOpticTile; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :engineId) (conj [:db/add id :copackaged_optics.ElectroOpticTile/engineId (get data :engineId)]))
                   (cond-> (contains? data :tileType) (conj [:db/add id :copackaged_optics.ElectroOpticTile/tileType (get data :tileType)]))
                   (cond-> (contains? data :channels) (conj [:db/add id :copackaged_optics.ElectroOpticTile/channels (as-long (get data :channels))]))
                   (cond-> (contains? data :powerPjPerBit) (conj [:db/add id :copackaged_optics.ElectroOpticTile/powerPjPerBit (as-double (get data :powerPjPerBit))]))
                   (conj [:db/add id :copackaged_optics.ElectroOpticTile/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-electro-optic-tile
  "Delete a ElectroOpticTile."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── FiberLink ────────────────────────────────────────────────────────────────
(defn create-fiber-link
  "Create a FiberLink."
  [port data]
  (require-fields data ["fiberType" "reachM"])
  (let [id (new-id "cpo_fib")
        e {:db/id id
           :copackaged_optics.FiberLink/id id
           :copackaged_optics.FiberLink/engineId (get data :engineId)
           :copackaged_optics.FiberLink/fiberType (get data :fiberType)
           :copackaged_optics.FiberLink/reachM (as-double (get data :reachM))
           :copackaged_optics.FiberLink/dataRateGbps (as-double (get data :dataRateGbps))
           :copackaged_optics.FiberLink/createdAt (now)
           :copackaged_optics.FiberLink/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-fiber-links
  "List FiberLink with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-fiber-links port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :copackaged_optics.FiberLink/id))
         rows (apply-filters rows (:filter opts) [:copackaged_optics.FiberLink/engineId :copackaged_optics.FiberLink/fiberType :copackaged_optics.FiberLink/reachM :copackaged_optics.FiberLink/dataRateGbps])]
     (paginate rows opts))))

(defn get-fiber-link
  "Retrieve a FiberLink by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-fiber-link port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-fiber-link
  "Update a FiberLink; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :engineId) (conj [:db/add id :copackaged_optics.FiberLink/engineId (get data :engineId)]))
                   (cond-> (contains? data :fiberType) (conj [:db/add id :copackaged_optics.FiberLink/fiberType (get data :fiberType)]))
                   (cond-> (contains? data :reachM) (conj [:db/add id :copackaged_optics.FiberLink/reachM (as-double (get data :reachM))]))
                   (cond-> (contains? data :dataRateGbps) (conj [:db/add id :copackaged_optics.FiberLink/dataRateGbps (as-double (get data :dataRateGbps))]))
                   (conj [:db/add id :copackaged_optics.FiberLink/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-fiber-link
  "Delete a FiberLink."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── SerdesLane ────────────────────────────────────────────────────────────────
(defn create-serdes-lane
  "Create a SerdesLane."
  [port data]
  (require-fields data ["index" "modulation"])
  (let [id (new-id "cpo_ser")
        e {:db/id id
           :copackaged_optics.SerdesLane/id id
           :copackaged_optics.SerdesLane/engineId (get data :engineId)
           :copackaged_optics.SerdesLane/index (as-long (get data :index))
           :copackaged_optics.SerdesLane/modulation (get data :modulation)
           :copackaged_optics.SerdesLane/dataRateGbps (as-double (get data :dataRateGbps))
           :copackaged_optics.SerdesLane/createdAt (now)
           :copackaged_optics.SerdesLane/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-serdes-lanes
  "List SerdesLane with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-serdes-lanes port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :copackaged_optics.SerdesLane/id))
         rows (apply-filters rows (:filter opts) [:copackaged_optics.SerdesLane/engineId :copackaged_optics.SerdesLane/index :copackaged_optics.SerdesLane/modulation :copackaged_optics.SerdesLane/dataRateGbps])]
     (paginate rows opts))))

(defn get-serdes-lane
  "Retrieve a SerdesLane by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-serdes-lane port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-serdes-lane
  "Update a SerdesLane; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :engineId) (conj [:db/add id :copackaged_optics.SerdesLane/engineId (get data :engineId)]))
                   (cond-> (contains? data :index) (conj [:db/add id :copackaged_optics.SerdesLane/index (as-long (get data :index))]))
                   (cond-> (contains? data :modulation) (conj [:db/add id :copackaged_optics.SerdesLane/modulation (get data :modulation)]))
                   (cond-> (contains? data :dataRateGbps) (conj [:db/add id :copackaged_optics.SerdesLane/dataRateGbps (as-double (get data :dataRateGbps))]))
                   (conj [:db/add id :copackaged_optics.SerdesLane/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-serdes-lane
  "Delete a SerdesLane."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── OpticalSwitch ────────────────────────────────────────────────────────────────
(defn create-optical-switch
  "Create a OpticalSwitch."
  [port data]
  (require-fields data ["radix" "technology"])
  (let [id (new-id "cpo_opt")
        e {:db/id id
           :copackaged_optics.OpticalSwitch/id id
           :copackaged_optics.OpticalSwitch/engineId (get data :engineId)
           :copackaged_optics.OpticalSwitch/radix (as-long (get data :radix))
           :copackaged_optics.OpticalSwitch/technology (get data :technology)
           :copackaged_optics.OpticalSwitch/insertionLossDb (as-double (get data :insertionLossDb))
           :copackaged_optics.OpticalSwitch/createdAt (now)
           :copackaged_optics.OpticalSwitch/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-optical-switches
  "List OpticalSwitch with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-optical-switches port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :copackaged_optics.OpticalSwitch/id))
         rows (apply-filters rows (:filter opts) [:copackaged_optics.OpticalSwitch/engineId :copackaged_optics.OpticalSwitch/radix :copackaged_optics.OpticalSwitch/technology :copackaged_optics.OpticalSwitch/insertionLossDb])]
     (paginate rows opts))))

(defn get-optical-switch
  "Retrieve a OpticalSwitch by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-optical-switch port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-optical-switch
  "Update a OpticalSwitch; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :engineId) (conj [:db/add id :copackaged_optics.OpticalSwitch/engineId (get data :engineId)]))
                   (cond-> (contains? data :radix) (conj [:db/add id :copackaged_optics.OpticalSwitch/radix (as-long (get data :radix))]))
                   (cond-> (contains? data :technology) (conj [:db/add id :copackaged_optics.OpticalSwitch/technology (get data :technology)]))
                   (cond-> (contains? data :insertionLossDb) (conj [:db/add id :copackaged_optics.OpticalSwitch/insertionLossDb (as-double (get data :insertionLossDb))]))
                   (conj [:db/add id :copackaged_optics.OpticalSwitch/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-optical-switch
  "Delete a OpticalSwitch."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── LinkBudget ────────────────────────────────────────────────────────────────
(defn create-link-budget
  "Create a LinkBudget."
  [port data]
  (require-fields data ["txPowerDbm" "rxSensitivityDbm"])
  (let [id (new-id "cpo_lin")
        e {:db/id id
           :copackaged_optics.LinkBudget/id id
           :copackaged_optics.LinkBudget/engineId (get data :engineId)
           :copackaged_optics.LinkBudget/txPowerDbm (as-double (get data :txPowerDbm))
           :copackaged_optics.LinkBudget/rxSensitivityDbm (as-double (get data :rxSensitivityDbm))
           :copackaged_optics.LinkBudget/marginDb (as-double (get data :marginDb))
           :copackaged_optics.LinkBudget/createdAt (now)
           :copackaged_optics.LinkBudget/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-link-budgets
  "List LinkBudget with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-link-budgets port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :copackaged_optics.LinkBudget/id))
         rows (apply-filters rows (:filter opts) [:copackaged_optics.LinkBudget/engineId :copackaged_optics.LinkBudget/txPowerDbm :copackaged_optics.LinkBudget/rxSensitivityDbm :copackaged_optics.LinkBudget/marginDb])]
     (paginate rows opts))))

(defn get-link-budget
  "Retrieve a LinkBudget by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-link-budget port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-link-budget
  "Update a LinkBudget; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :engineId) (conj [:db/add id :copackaged_optics.LinkBudget/engineId (get data :engineId)]))
                   (cond-> (contains? data :txPowerDbm) (conj [:db/add id :copackaged_optics.LinkBudget/txPowerDbm (as-double (get data :txPowerDbm))]))
                   (cond-> (contains? data :rxSensitivityDbm) (conj [:db/add id :copackaged_optics.LinkBudget/rxSensitivityDbm (as-double (get data :rxSensitivityDbm))]))
                   (cond-> (contains? data :marginDb) (conj [:db/add id :copackaged_optics.LinkBudget/marginDb (as-double (get data :marginDb))]))
                   (conj [:db/add id :copackaged_optics.LinkBudget/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-link-budget
  "Delete a LinkBudget."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/opticalengines" :op :create :entity "OpticalEngine"}
   {:method "GET" :path "/v1/opticalengines" :op :list :entity "OpticalEngine"}
   {:method "GET" :path "/v1/opticalengines/:id" :op :get :entity "OpticalEngine"}
   {:method "PATCH" :path "/v1/opticalengines/:id" :op :update :entity "OpticalEngine"}
   {:method "DELETE" :path "/v1/opticalengines/:id" :op :delete :entity "OpticalEngine"}
   {:method "POST" :path "/v1/electrooptictiles" :op :create :entity "ElectroOpticTile"}
   {:method "GET" :path "/v1/electrooptictiles" :op :list :entity "ElectroOpticTile"}
   {:method "GET" :path "/v1/electrooptictiles/:id" :op :get :entity "ElectroOpticTile"}
   {:method "PATCH" :path "/v1/electrooptictiles/:id" :op :update :entity "ElectroOpticTile"}
   {:method "DELETE" :path "/v1/electrooptictiles/:id" :op :delete :entity "ElectroOpticTile"}
   {:method "POST" :path "/v1/fiberlinks" :op :create :entity "FiberLink"}
   {:method "GET" :path "/v1/fiberlinks" :op :list :entity "FiberLink"}
   {:method "GET" :path "/v1/fiberlinks/:id" :op :get :entity "FiberLink"}
   {:method "PATCH" :path "/v1/fiberlinks/:id" :op :update :entity "FiberLink"}
   {:method "DELETE" :path "/v1/fiberlinks/:id" :op :delete :entity "FiberLink"}
   {:method "POST" :path "/v1/serdeslanes" :op :create :entity "SerdesLane"}
   {:method "GET" :path "/v1/serdeslanes" :op :list :entity "SerdesLane"}
   {:method "GET" :path "/v1/serdeslanes/:id" :op :get :entity "SerdesLane"}
   {:method "PATCH" :path "/v1/serdeslanes/:id" :op :update :entity "SerdesLane"}
   {:method "DELETE" :path "/v1/serdeslanes/:id" :op :delete :entity "SerdesLane"}
   {:method "POST" :path "/v1/opticalswitches" :op :create :entity "OpticalSwitch"}
   {:method "GET" :path "/v1/opticalswitches" :op :list :entity "OpticalSwitch"}
   {:method "GET" :path "/v1/opticalswitches/:id" :op :get :entity "OpticalSwitch"}
   {:method "PATCH" :path "/v1/opticalswitches/:id" :op :update :entity "OpticalSwitch"}
   {:method "DELETE" :path "/v1/opticalswitches/:id" :op :delete :entity "OpticalSwitch"}
   {:method "POST" :path "/v1/linkbudgets" :op :create :entity "LinkBudget"}
   {:method "GET" :path "/v1/linkbudgets" :op :list :entity "LinkBudget"}
   {:method "GET" :path "/v1/linkbudgets/:id" :op :get :entity "LinkBudget"}
   {:method "PATCH" :path "/v1/linkbudgets/:id" :op :update :entity "LinkBudget"}
   {:method "DELETE" :path "/v1/linkbudgets/:id" :op :delete :entity "LinkBudget"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"opticalengines" {:create create-optical-engine :list list-optical-engines :get get-optical-engine :update update-optical-engine :delete delete-optical-engine}
   "electrooptictiles" {:create create-electro-optic-tile :list list-electro-optic-tiles :get get-electro-optic-tile :update update-electro-optic-tile :delete delete-electro-optic-tile}
   "fiberlinks" {:create create-fiber-link :list list-fiber-links :get get-fiber-link :update update-fiber-link :delete delete-fiber-link}
   "serdeslanes" {:create create-serdes-lane :list list-serdes-lanes :get get-serdes-lane :update update-serdes-lane :delete delete-serdes-lane}
   "opticalswitches" {:create create-optical-switch :list list-optical-switches :get get-optical-switch :update update-optical-switch :delete delete-optical-switch}
   "linkbudgets" {:create create-link-budget :list list-link-budgets :get get-link-budget :update update-link-budget :delete delete-link-budget}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "copackaged_optics-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
